# ---
kind: pipeline
name: default
type: kubernetes
platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: ukhomeoffice/drone-docker
  settings:
    dockerfile: Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-postgres-alpine
    tags:
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push
