---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    repo: quay.io/ukhomeofficedigital/dq-postgres-alpine
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    dockerfile: Dockerfile
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event: push
